---
- name: Download Cantata
  get_url: >
    url=https://github.com/CDrummond/cantata/releases/download/v{{ cantata_version }}/{{ cantata_dmg }}
    dest={{ downloads_directory }}/{{ cantata_dmg }}

- name: Get current Cantata version
  shell: defaults read /Applications/Cantata.app/Contents/Info.plist CFBundleShortVersionString
  register: cantata_version_output
  ignore_errors: yes

- name: Mount Cantata image
  command: >
    chdir={{ downloads_directory }}
    hdiutil attach -nobrowse {{ cantata_dmg }}
  when: (cantata_version_output.rc == 1
         or cantata_version_output.stdout | version_compare(cantata_version, '<'))

- name: Copy Cantata.app to Applications directory
  command: >
    cp -R /Volumes/Cantata/Cantata.app /Applications
  become: yes
  when: (cantata_version_output.rc == 1
         or cantata_version_output.stdout | version_compare(cantata_version, '<'))

- name: Unmount Cantata image
  command: hdiutil detach /Volumes/Cantata
  when: (cantata_version_output.rc == 1
         or cantata_version_output.stdout | version_compare(cantata_version, '<'))
