---
- name: Download Emacs
  get_url: >
    url=https://emacsformacosx.com/emacs-builds/Emacs-25.1-1-universal.dmg
    dest={{ downloads_directory }}/Emacs-25.1-1-universal.dmg

- name: Mount the Emacs image
  command: >
    chdir={{ downloads_directory }}
    hdiutil attach Emacs-25.1-1-universal.dmg
    creates=/Volumes/Emacs

- name: Install Emacs
  command: >
    cp -R /Volumes/Emacs/Emacs.app /Applications
    creates=/Applications/Emacs.app
  sudo: yes

- name: Unmount the Emacs image
  command: hdiutil detach /Volumes/Emacs
