---
- name: Download Terraform archive
  get_url:
    url: "{{ terraform_zip_url }}"
    dest: "{{ downloads_directory }}/{{ terraform_zip }}"
    checksum: "{{ terraform_checksum }}"

- name: Extract Terraform archive
  command: >
    chdir={{ downloads_directory }}
    unzip -fou {{ terraform_zip }} -d {{ downloads_directory }}

- name: Install Terraform
  command: cp "{{ downloads_directory }}/{{ terraform_binary_name }}" /usr/local/bin
