---
- name: Download Theremin
  get_url: >
    url=http://f.nn.lv/ms/l5/29/Theremin.app.zip
    dest={{ downloads_directory }}/Theremin.app.zip

- name: Extract Theremin zip archive
  command: >
    chdir={{ downloads_directory }}
    unzip Theremin.app.zip -d Theremin.app
    creates=Theremin.app

- name: Copy Theremin.app to Applications directory
  command: >
    cp -R {{ downloads_directory }}/Theremin.app/Theremin.app /Applications
    creates=/Applications/Theremin.app
  sudo: yes
