---
- name: Download iTerm
  get_url: >
    url=http://www.iterm2.com/nightly/iTerm2-1_0_0_20131221-nightly.zip
    dest={{ downloads_directory }}/iTerm2-1_0_0_20131221-nightly.zip

- name: Extract iTerm zip archive
  command: >
    chdir={{ downloads_directory }}
    unzip iTerm2-1_0_0_20131221-nightly.zip -d iTerm2-1_0_0_20131221-nightly
    creates=iTerm2-1_0_0_20131221-nightly

- name: Copy iTerm.app to Applications directory
  command: >
    cp -R {{ downloads_directory }}/iTerm2-1_0_0_20131221-nightly/iTerm.app /Applications
    creates=/Applications/iTerm.app
  sudo: yes
